name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest  # Use the latest stable Ubuntu runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Correct action to check out the code

      - name: Set up Node.js
        uses: actions/setup-node@v3  # Setup Node.js to ensure the correct version of Node.js is used
        with:
          node-version: '16'  # This makes sure Node 16 is used, as per your requirements

      - name: Install dependencies
        run: npm install  # Installs the dependencies from package.json

      - name: Run tests
        run: npm test  # Runs the tests as defined in the package.json file
